# Generated by Django 4.1.1 on 2022-10-08 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('AsesorId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=500)),
                ('Telefono', models.CharField(max_length=10)),
                ('Correo', models.CharField(max_length=256)),
                ('Prospectos', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('prospectoId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('correo', models.EmailField(max_length=254)),
                ('nss', models.CharField(blank=True, max_length=11, null=True)),
                ('curp', models.CharField(blank=True, max_length=18, null=True)),
                ('vivienda', models.CharField(blank=True, max_length=256, null=True)),
                ('fraccionamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('cotizacion', models.CharField(blank=True, max_length=256, null=True)),
                ('recomendacion', models.CharField(blank=True, max_length=256, null=True)),
                ('estatus', models.CharField(blank=True, max_length=100, null=True)),
                ('asesor', models.CharField(blank=True, max_length=100, null=True)),
                ('plazo', models.CharField(blank=True, max_length=256, null=True)),
                ('enganche', models.CharField(blank=True, max_length=100, null=True)),
                ('precioCasa', models.CharField(blank=True, max_length=100, null=True)),
                ('registro', models.DateField(default=datetime.date.today)),
                ('satisfaccion', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vivienda',
            fields=[
                ('viviendaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=500, null=True)),
                ('precio', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicas', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('fraccionamiento', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
